{
 "title": "Sales",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "# Análise Geral de Vendas e Receitas 📊"
   }
  },
  {
   "type": "orchestracities-iconstat-panel",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    pro.brand AS marca,\r\n    COUNT(fun.paid_date) AS \"vendas (#)\",\r\n    TO_CHAR(SUM(pro.price), 'FM999G999G999G999D00') AS \"- Preço Total de Vendas\"\r\n    \r\nFROM sales.funnel AS fun\r\nLEFT JOIN sales.products AS pro\r\n    ON fun.product_id = pro.product_id\r\nWHERE paid_date BETWEEN '2021-08-01' AND '2021-08-31'\r\n  AND pro.brand = 'FIAT'\r\nGROUP BY marca;\r\n"
    }
   ]
  },
  {
   "type": "orchestracities-iconstat-panel",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    pro.brand AS marca,\r\n    COUNT(fun.paid_date) AS \"vendas (#)\",\r\n    TO_CHAR(SUM(pro.price), 'FM999G999G999G999D00') AS \"- Preço Total de Vendas\"\r\n    \r\nFROM sales.funnel AS fun\r\nLEFT JOIN sales.products AS pro\r\n    ON fun.product_id = pro.product_id\r\nWHERE paid_date BETWEEN '2021-08-01' AND '2021-08-31'\r\n  AND pro.brand = 'CHEVROLET'\r\nGROUP BY marca;\r\n"
    }
   ]
  },
  {
   "type": "orchestracities-iconstat-panel",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    pro.brand AS marca,\r\n    COUNT(fun.paid_date) AS \"vendas (#)\",\r\n    TO_CHAR(SUM(pro.price), 'FM999G999G999G999D00') AS \"- Preço Total de Vendas\"\r\n    \r\nFROM sales.funnel AS fun\r\nLEFT JOIN sales.products AS pro\r\n    ON fun.product_id = pro.product_id\r\nWHERE paid_date BETWEEN '2021-08-01' AND '2021-08-31'\r\n  AND pro.brand = 'VOLKSWAGEN'\r\nGROUP BY marca;\r\n"
    }
   ]
  },
  {
   "title": "Vendas por Estado",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'Brazil' AS país,\r\n    cus.state AS estado,\r\n    COUNT(fun.paid_date) AS \"vendas (#)\",\r\n    CASE \r\n        WHEN cus.state = 'SP' THEN -23.5505\r\n        WHEN cus.state = 'RJ' THEN -22.9068\r\n        WHEN cus.state = 'MG' THEN -19.9286\r\n        WHEN cus.state = 'BA' THEN -12.9714\r\n        WHEN cus.state = 'RS' THEN -30.0346\r\n        WHEN cus.state = 'SC' THEN -27.5954\r\n        -- Adicione outros estados, se necessário\r\n        ELSE NULL\r\n    END AS latitude,\r\n    CASE \r\n        WHEN cus.state = 'SP' THEN -46.6333\r\n        WHEN cus.state = 'RJ' THEN -43.1729\r\n        WHEN cus.state = 'MG' THEN -43.9378\r\n        WHEN cus.state = 'BA' THEN -38.5014\r\n        WHEN cus.state = 'RS' THEN -51.2177\r\n        WHEN cus.state = 'SC' THEN -48.5480\r\n        ELSE NULL\r\n    END AS longitude\r\nFROM sales.funnel AS fun\r\nLEFT JOIN sales.customers AS cus\r\n    ON fun.customer_id = cus.customer_id\r\nWHERE paid_date BETWEEN '2021-08-01' AND '2021-08-31'\r\nGROUP BY país, estado\r\nORDER BY \"vendas (#)\" DESC\r\nLIMIT 5;\r\n"
    }
   ]
  },
  {
   "title": "Marcas Mais Vendidas",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\r\n\tpro.brand as marca,\r\n\tcount(fun.paid_date) as \"vendas (#)\"\r\n\r\nfrom sales.funnel as fun\r\nleft join sales.products as pro\r\n\ton fun.product_id = pro.product_id\r\nwhere paid_date between '2021-08-01' and '2021-08-31'\r\ngroup by marca\r\norder by \"vendas (#)\" desc\r\nlimit 5\r\n"
    }
   ]
  },
  {
   "title": "Visitas no Site",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 2 },
   "targets": [
    {
     "rawSql": "select\r\n\textract('dow' from visit_page_date) as dia_semana,\r\n\tcase \r\n\t\twhen extract('dow' from visit_page_date)=0 then 'Domingo'\r\n\t\twhen extract('dow' from visit_page_date)=1 then 'Segunda-feira'\r\n\t\twhen extract('dow' from visit_page_date)=2 then 'Terça-feira'\r\n\t\twhen extract('dow' from visit_page_date)=3 then 'Quarta-feira'\r\n\t\twhen extract('dow' from visit_page_date)=4 then 'Quinta-feira'\r\n\t\twhen extract('dow' from visit_page_date)=5 then 'Sexta-feira'\r\n\t\twhen extract('dow' from visit_page_date)=6 then 'Sábado'\r\n\t\telse null end as \"dia da semana\",\r\n\tcount(*) as \"visitas (#)\"\r\n\r\nfrom sales.funnel\r\nwhere visit_page_date between '2021-08-01' and '2021-08-31'\r\ngroup by dia_semana \r\norder by \"visitas (#)\" desc\r\n\r\n"
    }
   ]
  },
  {
   "title": "Top 10 Lojas",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select\r\n\tsto.store_name as loja,\r\n\tcount(fun.paid_date) as \"vendas (#)\"\r\n\r\nfrom sales.funnel as fun\r\nleft join sales.stores as sto\r\n\ton fun.store_id = sto.store_id\r\nwhere paid_date between '2021-08-01' and '2021-08-31'\r\ngroup by loja\r\norder by \"vendas (#)\" desc\r\nlimit 10\r\n"
    }
   ]
  },
  {
   "title": "Leads, Vendas, Receita, Conversão e Ticket Médio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "with \r\n\tleads as (\r\n\t\tselect\r\n\t\t\tdate_trunc('month', visit_page_date)::date as visit_page_month,\r\n\t\t\tcount(*) as visit_page_count\r\n\t\tfrom sales.funnel\r\n\t\tgroup by visit_page_month\r\n\t\torder by visit_page_month\r\n\t),\r\n\t\r\n\tpayments as (\r\n\t\tselect\r\n\t\t\tdate_trunc('month', fun.paid_date)::date as paid_month,\r\n\t\t\tcount(fun.paid_date) as paid_count,\r\n\t\t\tsum(pro.price * (1+fun.discount)) as receita\r\n\t\tfrom sales.funnel as fun\r\n\t\tleft join sales.products as pro\r\n\t\t\ton fun.product_id = pro.product_id\r\n\t\twhere fun.paid_date is not null\r\n\t\tgroup by paid_month\r\n\t\torder by paid_month\r\n\t)\r\n\t\r\nselect\r\n\tleads.visit_page_month as \"Mês\",\r\n\tleads.visit_page_count as \"Leads\",\r\n\tpayments.paid_count as \"Vendas\",\r\n\t(payments.receita/1000) as \"Receita (k, R$)\",\r\n\t(payments.paid_count::float/leads.visit_page_count::float) as \"Conversão (%)\",\r\n\t(payments.receita/payments.paid_count/1000) as \"Ticket Médio (k, R$)\"\r\n\r\nfrom leads\r\nleft join payments\r\n\ton leads.visit_page_month = paid_month"
    }
   ]
  }
 ]
}